# Generated by Django 4.0.4 on 2022-05-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.IntegerField()),
                ('adminUsername', models.IntegerField()),
                ('adminPassword', models.CharField(max_length=255)),
                ('adminName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Busses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.IntegerField()),
                ('busPlateNumber', models.CharField(max_length=255)),
                ('busDriver', models.CharField(max_length=255)),
                ('numberOfSeats', models.IntegerField()),
                ('numberOfVacancies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiefID', models.IntegerField()),
                ('chiefUsername', models.CharField(max_length=255)),
                ('chiefPassword', models.CharField(max_length=255)),
                ('chiefName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('studentID', models.IntegerField()),
                ('studentName', models.CharField(max_length=255)),
                ('busID', models.IntegerField()),
                ('scheduleID', models.IntegerField()),
                ('scheduleSeatVacancies', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleID', models.IntegerField()),
                ('busID', models.IntegerField()),
                ('scheduleDeparture', models.TimeField()),
                ('scheduleArrival', models.TimeField()),
                ('scheduleSeatVacancies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('studentName', models.CharField(max_length=255)),
                ('studentCourse', models.CharField(max_length=255)),
                ('studentEmail', models.CharField(max_length=255)),
                ('studentUsername', models.CharField(max_length=255)),
                ('studentPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
